### PR TITLE
Add parameters to specify label formats

### PR DESCRIPTION
**Pull request by chmgr**
Yet it was not possible to specify different label formats. This PR adds these parameters for `createShipments()`

### CODE REVIEW

**Comment by mam08ixo** [comment]
Hi @chmgr, thank you for your contribution. Could you please explain the use case of this change? What is the benefit compared to the _DHL Business Customer Portal_ web interface setting?

dhl_printer_settings

**Comment by chmgr** [comment]
These parameters allow to set the label formats independently from the settings made in the web portal. This is very useful, when:
* the application requires a specific format, which should not be corrupted by portal setting changes
* the application is used on different clients with different printers and paper/label sizes

**Comment by ngolatka** [comment]
@chmgr 
Usually we expect a separate API user to be created in the DHL portal which then gets used in the Magento configuration. That API use can have its own printer settings in the DHL portal, fulfilling both your usage scenarions (imho).

**Comment by chmgr** [comment]
> Usually we expect a separate API user to be created in the DHL portal which then gets used in the Magento configuration. That API use can have its own printer settings in the DHL portal, fulfilling both your usage scenarions (imho).

Actually I looked at the package as a more general SDK, not for a specific use case. If it's only intended for your use-case in your Magento module, that's ok....

however but that's not the we we use it...

**Comment by mam08ixo** [comment]
@chmgr Yes, this is a general purpose SDK, not limited to a certain platform.

> the application requires a specific format, which should not be corrupted by portal setting changes

I think this is a perfect use case for differently configured API users like @ngolatka pointed out.

> the application is used on different clients with different printers and paper/label sizes

Valid, if that is actually happening in the wild.

So here are a few issues that I have with the current implementation:

1. To encourage usage of the extra settings, the [service's interface](https://github.com/netresearch/dhl-sdk-api-bcs/blob/1.3.0/src/Api/ShipmentServiceInterface.php#L46) must be aligned. Major version number will then be increased.
2. The change is tailored to your very individual requirements. If we incorporate the feature, then I would rather pass a configuration object that holds all additional settings (`labelResponseType`, `groupProfileName`, `labelFormat`, `labelFormatRetoure`, `combinedPrinting`).
3. The test only proves that the method accepts arbitrary additional arguments but does not validate if the correct value ends up in the web service request at the correct position (field).

Please let me know if using separate API users per application is good enough for you or if we want to continue here. Thank you!

**Comment by mam08ixo** [comment]
SDK version [2.0.0](https://github.com/netresearch/dhl-sdk-api-bcs/releases/tag/2.0.0) allows to configure print format and other settings. See [usage example in README](https://github.com/netresearch/dhl-sdk-api-bcs/blob/2.0.0/README.md#usage-1).

**Pull request closed without merging**
