### PR TITLE
prevent `Value expected to be 'array', but 'array' given`

### PR DESCRIPTION
**Pull request by xerc**
in the style of ..
https://github.com/netresearch/dhl-sdk-api-bcs/blob/2ae9459388b136db92f9eb4a1883960b18e0b3b6/src/Service/ShipmentService.php#L85-L90
https://github.com/netresearch/dhl-sdk-api-bcs/blob/2ae9459388b136db92f9eb4a1883960b18e0b3b6/src/Service/ShipmentService.php#L112-L117

### CODE REVIEW

**Comment by Sebastian80** [comment]
Hi @xerc , thank you for your contribution.
Is there any way we can provoke the said error ?

Best reagrds, 
Sebastian E.

**Comment by xerc** [comment]
via non-integer array keys `->validateShipments(['x' => (array), 'y' => (array)]`)`

**Comment by xerc** [comment]
your SDK does it within the XML generator (snippeds above) but not for REST => thefore my adaptation

**Comment by Sebastian80** [comment]
Hi @xerc,

you are correct, we did that a while back for the soap request.
After your PR and checking the code, we came to the conclusion that such things should happen outside of the sdk.
We will refactor this.

best regards,
Sebastian E.

Internal Ref: DHLGW-1380

**Pull request closed without merging**
