### PR TITLE
Update YAML schema file to v2.1.8

### PR DESCRIPTION
**Pull request by xerc**
ref. https://developer.dhl.com/sites/default/files/2024-01/parcel-de-shipping-v2_0.yaml

CLEANUP/

`/\r/` => `null`
`/\s+$/` => `null`

IMPORTANT/ there where some BUGs ..

[DHL#19386] `hscode` => `hsCode`
[DHL#19398] `/^(\s+)enum:\n\1\s{4}/` => `$1enum:\n$1\s{2}` incl. all following lines

### CODE REVIEW

**Comment by xerc** [comment]
`2.1.7` they droped ; did not touch
https://github.com/netresearch/dhl-sdk-api-bcs/blob/2ae9459388b136db92f9eb4a1883960b18e0b3b6/src/Http/ClientPlugin/DHL_Parcel_DE_Shipping-v2.1.6.yaml#L1375-L1383

**Comment by xerc** [comment]
they got the same infos (same day) after this commit ; "looking into it" [DHL ticket ID] incl. bugs @ developer HowTo

**Comment by xerc** [comment]
ref. https://developer.dhl.com/sites/default/files/2024-03/parcel-de-shipping-v2_0.yaml

DHL changed `print format` without changing the version!

**Comment by powli** [comment]
Hello @xerc, we released a new SDK without the SOAP API integration as it is going to be phased out in the future - it also has the updated schema files. I'd recommend you switch to the new SDK if you do not need the SOAP API.

New SDK: https://github.com/netresearch/sdk-api-parcel-de

**Comment by xerc** [comment]
thanks for the info ; already impl. & switched to REST (native)

**Pull request closed without merging**
